use rusqlite::{params, Connection, OptionalExtension, Result};
use serde::{Deserialize, Serialize};
use std::path::PathBuf;
use std::sync::{Arc, Mutex};
use tracing::{debug, info, warn};

use crate::error::GremlinError;

/// A stored conversation message with metadata
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct StoredMessage {
    pub id: i64,
    pub session_id: String,
    pub role: String,           // "user" | "assistant" | "system" | "tool"
    pub content: String,
    pub project: Option<String>,
    pub tokens: Option<i64>,
    pub created_at: String,
}

/// A learned fact about the user/project
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Fact {
    pub id: i64,
    pub key: String,
    pub value: String,
    pub project: Option<String>,
    pub confidence: f32,        // 0.0 - 1.0
    pub source: String,         // "conversation" | "explicit" | "observed"
    pub created_at: String,
    pub updated_at: String,
}

/// A learned user preference
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Preference {
    pub id: i64,
    pub key: String,
    pub value: String,
    pub project: Option<String>,
    pub confidence: f32,
    pub source: String,         // "explicit" | "inferred" | "observed"
    pub created_at: String,
    pub updated_at: String,
}

/// A recommendation generated by the memory system
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Recommendation {
    pub id: i64,
    pub kind: String,           // "command" | "tool" | "workflow" | "code_change"
    pub title: String,
    pub description: String,
    pub confidence: f32,
    pub context: String,        // JSON context that triggered this
    pub action: Option<String>, // tool call JSON if actionable
    pub created_at: String,
    pub dismissed: bool,
}

/// A proposed self-modification
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct SelfModification {
    pub id: i64,
    pub kind: String,           // "code_change" | "config_change" | "tool_addition"
    pub title: String,
    pub description: String,
    pub diff: String,           // unified diff
    pub confidence: f32,
    pub status: String,         // "proposed" | "approved" | "rejected" | "applied"
    pub created_at: String,
    pub decided_at: Option<String>,
}

/// Vector embedding for semantic search
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Embedding {
    pub id: i64,
    pub message_id: i64,
    pub vector: Vec<f32>,       // 384-dim for all-MiniLM-L6-v2
    pub created_at: String,
}

/// Memory database handle
pub struct Memory {
    conn: Arc<Mutex<Connection>>,
}

impl Memory {
    /// Initialize the memory database
    pub fn new(data_dir: &PathBuf) -> Result<Self, GremlinError> {
        std::fs::create_dir_all(data_dir)?;
        let db_path = data_dir.join("memory.db");
        let conn = Connection::open(&db_path)?;
        
        // Enable WAL mode for better concurrency
        conn.pragma_update(None, "journal_mode", "WAL")?;
        conn.pragma_update(None, "synchronous", "NORMAL")?;
        
        let mem = Self { conn: Arc::new(Mutex::new(conn)) };
        mem.init_schema()?;
        mem.init_vec_extension()?;
        mem.migrate_from_json()?;
        Ok(mem)
    }

    fn init_schema(&self) -> Result<(), GremlinError> {
        let conn = self.conn.lock().unwrap();
        
        // Conversations table with FTS5
        conn.execute_batch(r#"
            CREATE TABLE IF NOT EXISTS conversations (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                session_id TEXT NOT NULL,
                role TEXT NOT NULL,
                content TEXT NOT NULL,
                project TEXT,
                tokens INTEGER,
                created_at TEXT NOT NULL DEFAULT (datetime('now'))
            );

            CREATE VIRTUAL TABLE IF NOT EXISTS conversations_fts USING fts5(
                content, project, session_id,
                content='conversations', content_rowid='id',
                tokenize='porter unicode61'
            );

            CREATE TRIGGER IF NOT EXISTS conversations_ai AFTER INSERT ON conversations BEGIN
                INSERT INTO conversations_fts(rowid, content, project, session_id)
                VALUES (new.id, new.content, new.project, new.session_id);
            END;

            CREATE TRIGGER IF NOT EXISTS conversations_ad AFTER DELETE ON conversations BEGIN
                INSERT INTO conversations_fts(conversations_fts, rowid, content, project, session_id)
                VALUES ('delete', old.id, old.content, old.project, old.session_id);
            END;

            CREATE TRIGGER IF NOT EXISTS conversations_au AFTER UPDATE ON conversations BEGIN
                INSERT INTO conversations_fts(conversations_fts, rowid, content, project, session_id)
                VALUES ('delete', old.id, old.content, old.project, old.session_id);
                INSERT INTO conversations_fts(rowid, content, project, session_id)
                VALUES (new.id, new.content, new.project, new.session_id);
            END;
        "#)?;

        // Facts table
        conn.execute_batch(r#"
            CREATE TABLE IF NOT EXISTS facts (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                key TEXT NOT NULL,
                value TEXT NOT NULL,
                project TEXT,
                confidence REAL NOT NULL DEFAULT 0.5,
                source TEXT NOT NULL DEFAULT 'conversation',
                created_at TEXT NOT NULL DEFAULT (datetime('now')),
                updated_at TEXT NOT NULL DEFAULT (datetime('now')),
                UNIQUE(key, project)
            );

            CREATE INDEX IF NOT EXISTS idx_facts_project ON facts(project);
            CREATE INDEX IF NOT EXISTS idx_facts_key ON facts(key);
        "#)?;

        // Preferences table
        conn.execute_batch(r#"
            CREATE TABLE IF NOT EXISTS preferences (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                key TEXT NOT NULL,
                value TEXT NOT NULL,
                project TEXT,
                confidence REAL NOT NULL DEFAULT 0.5,
                source TEXT NOT NULL DEFAULT 'inferred',
                created_at TEXT NOT NULL DEFAULT (datetime('now')),
                updated_at TEXT NOT NULL DEFAULT (datetime('now')),
                UNIQUE(key, project)
            );

            CREATE INDEX IF NOT EXISTS idx_preferences_project ON preferences(project);
            CREATE INDEX IF NOT EXISTS idx_preferences_key ON preferences(key);
        "#)?;

        // Recommendations table
        conn.execute_batch(r#"
            CREATE TABLE IF NOT EXISTS recommendations (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                kind TEXT NOT NULL,
                title TEXT NOT NULL,
                description TEXT NOT NULL,
                confidence REAL NOT NULL DEFAULT 0.5,
                context TEXT NOT NULL DEFAULT '{}',
                action TEXT,
                created_at TEXT NOT NULL DEFAULT (datetime('now')),
                dismissed BOOLEAN NOT NULL DEFAULT 0
            );

            CREATE INDEX IF NOT EXISTS idx_recommendations_dismissed ON recommendations(dismissed);
        "#)?;

        // Self-modifications table
        conn.execute_batch(r#"
            CREATE TABLE IF NOT EXISTS self_modifications (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                kind TEXT NOT NULL,
                title TEXT NOT NULL,
                description TEXT NOT NULL,
                diff TEXT NOT NULL,
                confidence REAL NOT NULL DEFAULT 0.5,
                status TEXT NOT NULL DEFAULT 'proposed',
                created_at TEXT NOT NULL DEFAULT (datetime('now')),
                decided_at TEXT
            );

            CREATE INDEX IF NOT EXISTS idx_self_mod_status ON self_modifications(status);
        "#)?;

        // Embeddings table (for vector search via sqlite-vec)
        conn.execute_batch(r#"
            CREATE TABLE IF NOT EXISTS embeddings (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                message_id INTEGER NOT NULL,
                vector BLOB NOT NULL,  -- sqlite-vec format
                created_at TEXT NOT NULL DEFAULT (datetime('now')),
                FOREIGN KEY(message_id) REFERENCES conversations(id) ON DELETE CASCADE
            );

            CREATE INDEX IF NOT EXISTS idx_embeddings_message ON embeddings(message_id);
        "#)?;

        // Create triggers for auto-embedding (requires sqlite-vec)
        // Note: Actual embedding generation happens in background service

        Ok(())
    }

    fn init_vec_extension(&self) -> Result<(), GremlinError> {
        let conn = self.conn.lock().unwrap();
        // Try to load sqlite-vec extension for vector search
        // This is optional - if not available, vector search is disabled
        unsafe {
            let _ = conn.load_extension("vec0", Some("sqlite3_vec_init"));
        }
        Ok(())
    }

    /// Migrate existing conversation.json to SQLite
    fn migrate_from_json(&self) -> Result<(), GremlinError> {
        let json_path = dirs::config_dir()
            .map(|d| d.join("gremlin").join("conversation.json"));
        
        if let Some(path) = json_path {
            if path.exists() {
                let content = std::fs::read_to_string(&path)?;
                if let Ok(messages) = serde_json::from_str::<Vec<crate::ollama::Message>>(&content) {
                    let conn = self.conn.lock().unwrap();
                    let mut count = 0;
                    for msg in messages {
                        if msg.role != "system" { // Skip system messages
                            conn.execute(
                                "INSERT INTO conversations (session_id, role, content, created_at) VALUES (?, ?, ?, datetime('now'))",
                                params!["migrated", msg.role, msg.content]
                            )?;
                            count += 1;
                        }
                    }
                    if count > 0 {
                        info!("Migrated {} messages from conversation.json", count);
                    }
                }
            }
        }
        Ok(())
    }

    // ─── Conversation operations ───

    /// Store a message
    pub fn save_message(&self, session_id: &str, role: &str, content: &str, project: Option<&str>, tokens: Option<i64>) -> Result<i64, GremlinError> {
        let conn = self.conn.lock().unwrap();
        conn.execute(
            "INSERT INTO conversations (session_id, role, content, project, tokens) VALUES (?, ?, ?, ?, ?)",
            params![session_id, role, content, project, tokens]
        )?;
        Ok(conn.last_insert_rowid())
    }

    /// Load recent conversation history for a session
    pub fn load_recent(&self, session_id: &str, limit: usize) -> Result<Vec<StoredMessage>, GremlinError> {
        let conn = self.conn.lock().unwrap();
        let mut stmt = conn.prepare(
            "SELECT id, session_id, role, content, project, tokens, created_at
             FROM conversations
             WHERE session_id = ?
             ORDER BY id DESC
             LIMIT ?"
        )?;
        let rows = stmt.query_map(params![session_id, limit], |row| {
            Ok(StoredMessage {
                id: row.get(0)?,
                session_id: row.get(1)?,
                role: row.get(2)?,
                content: row.get(3)?,
                project: row.get(4)?,
                tokens: row.get(5)?,
                created_at: row.get(6)?,
            })
        })?;
        Ok(rows.filter_map(Result::ok).collect())
    }

    /// Full-text search over conversations
    pub fn search(&self, query: &str, project: Option<&str>, limit: usize) -> Result<Vec<StoredMessage>, GremlinError> {
        let conn = self.conn.lock().unwrap();
        if let Some(proj) = project {
            let mut stmt = conn.prepare(
                "SELECT c.id, c.session_id, c.role, c.content, c.project, c.tokens, c.created_at
                 FROM conversations_fts f
                 JOIN conversations c ON c.id = f.rowid
                 WHERE f.content MATCH ? AND (c.project = ? OR c.project IS NULL)
                 ORDER BY rank
                 LIMIT ?"
            )?;
            let rows = stmt.query_map(params![query, project, limit as i64], |row| {
                Ok(StoredMessage {
                    id: row.get(0)?,
                    session_id: row.get(1)?,
                    role: row.get(2)?,
                    content: row.get(3)?,
                    project: row.get(4)?,
                    tokens: row.get(5)?,
                    created_at: row.get(6)?,
                })
            })?;
            Ok(rows.filter_map(Result::ok).collect())
        } else {
            let mut stmt = conn.prepare(
                "SELECT c.id, c.session_id, c.role, c.content, c.project, c.tokens, c.created_at
                 FROM conversations_fts f
                 JOIN conversations c ON c.id = f.rowid
                 WHERE f.content MATCH ?
                 ORDER BY rank
                 LIMIT ?"
            )?;
            let rows = stmt.query_map(params![query, limit as i64], |row| {
                Ok(StoredMessage {
                    id: row.get(0)?,
                    session_id: row.get(1)?,
                    role: row.get(2)?,
                    content: row.get(3)?,
                    project: row.get(4)?,
                    tokens: row.get(5)?,
                    created_at: row.get(6)?,
                })
            })?;
            Ok(rows.filter_map(Result::ok).collect())
        }
    }

    // ─── Fact operations ───

    /// Get or create a fact
    pub fn upsert_fact(&self, key: &str, value: &str, project: Option<&str>, confidence: f32, source: &str) -> Result<i64, GremlinError> {
        let conn = self.conn.lock().unwrap();
        let now = chrono::Utc::now().to_rfc3339();
        conn.execute(
            r#"
            INSERT INTO facts (key, value, project, confidence, source, created_at, updated_at)
            VALUES (?, ?, ?, ?, ?, ?, ?)
            ON CONFLICT(key, project) DO UPDATE SET
                value = excluded.value,
                confidence = CASE WHEN excluded.confidence > facts.confidence THEN excluded.confidence ELSE facts.confidence END,
                source = excluded.source,
                updated_at = excluded.updated_at
            "#,
            params![key, value, project, confidence, source, chrono::Utc::now().to_rfc3339(), chrono::Utc::now().to_rfc3339()]
        )?;
        Ok(conn.last_insert_rowid())
    }

    pub fn get_fact(&self, key: &str, project: Option<&str>) -> Result<Option<Fact>, GremlinError> {
        let conn = self.conn.lock().unwrap();
        if let Some(p) = project {
            let mut stmt = conn.prepare(
                "SELECT id, key, value, project, confidence, source, created_at, updated_at FROM facts WHERE key = ? AND project = ?"
            )?;
            let mut rows = stmt.query_map(params![key, project], |row| {
                Ok(Fact {
                    id: row.get(0)?,
                    key: row.get(1)?,
                    value: row.get(2)?,
                    project: row.get(3)?,
                    confidence: row.get(4)?,
                    source: row.get(5)?,
                    created_at: row.get(6)?,
                    updated_at: row.get(7)?,
                })
            })?;
            Ok(rows.next().transpose()?)
        } else {
            let mut stmt = conn.prepare(
                "SELECT id, key, value, project, confidence, source, created_at, updated_at FROM facts WHERE key = ? AND project IS NULL"
            )?;
            let mut rows = stmt.query_map(params![key], |row| {
                Ok(Fact {
                    id: row.get(0)?,
                    key: row.get(1)?,
                    value: row.get(2)?,
                    project: row.get(3)?,
                    confidence: row.get(4)?,
                    source: row.get(5)?,
                    created_at: row.get(6)?,
                    updated_at: row.get(7)?,
                })
            })?;
            Ok(rows.next().transpose()?)
        }
    }

    pub fn list_facts(&self, project: Option<&str>) -> Result<Vec<Fact>, GremlinError> {
        let conn = self.conn.lock().unwrap();
        if let Some(p) = project {
            let mut stmt = conn.prepare(
                "SELECT id, key, value, project, confidence, source, created_at, updated_at FROM facts WHERE project = ? ORDER BY confidence DESC"
            )?;
            let rows = stmt.query_map(params![project], |row| {
                Ok(Fact {
                    id: row.get(0)?,
                    key: row.get(1)?,
                    value: row.get(2)?,
                    project: row.get(3)?,
                    confidence: row.get(4)?,
                    source: row.get(5)?,
                    created_at: row.get(6)?,
                    updated_at: row.get(7)?,
                })
            })?;
            Ok(rows.filter_map(Result::ok).collect())
        } else {
            let mut stmt = conn.prepare(
                "SELECT id, key, value, project, confidence, source, created_at, updated_at FROM facts ORDER BY confidence DESC"
            )?;
            let rows = stmt.query_map([], |row| {
                Ok(Fact {
                    id: row.get(0)?,
                    key: row.get(1)?,
                    value: row.get(2)?,
                    project: row.get(3)?,
                    confidence: row.get(4)?,
                    source: row.get(5)?,
                    created_at: row.get(6)?,
                    updated_at: row.get(7)?,
                })
            })?;
            Ok(rows.filter_map(Result::ok).collect())
        }
    }

    // ─── Preference operations ───

    pub fn upsert_preference(&self, key: &str, value: &str, project: Option<&str>, confidence: f32, source: &str) -> Result<i64, GremlinError> {
        let conn = self.conn.lock().unwrap();
        conn.execute(
            r#"
            INSERT INTO preferences (key, value, project, confidence, source, created_at, updated_at)
            VALUES (?, ?, ?, ?, ?, ?, ?)
            ON CONFLICT(key, project) DO UPDATE SET
                value = excluded.value,
                confidence = CASE WHEN excluded.confidence > preferences.confidence THEN excluded.confidence ELSE preferences.confidence END,
                source = excluded.source,
                updated_at = excluded.updated_at
            "#,
            params![key, value, project, confidence, source, chrono::Utc::now().to_rfc3339(), chrono::Utc::now().to_rfc3339()]
        )?;
        Ok(conn.last_insert_rowid())
    }

    pub fn get_preference(&self, key: &str, project: Option<&str>) -> Result<Option<Preference>, GremlinError> {
        let conn = self.conn.lock().unwrap();
        if let Some(p) = project {
            let mut stmt = conn.prepare(
                "SELECT id, key, value, project, confidence, source, created_at, updated_at FROM preferences WHERE key = ? AND project = ?"
            )?;
            let mut rows = stmt.query_map(params![key, project], |row| {
                Ok(Preference {
                    id: row.get(0)?,
                    key: row.get(1)?,
                    value: row.get(2)?,
                    project: row.get(3)?,
                    confidence: row.get(4)?,
                    source: row.get(5)?,
                    created_at: row.get(6)?,
                    updated_at: row.get(7)?,
                })
            })?;
            Ok(rows.next().transpose()?)
        } else {
            let mut stmt = conn.prepare(
                "SELECT id, key, value, project, confidence, source, created_at, updated_at FROM preferences WHERE key = ? AND project IS NULL"
            )?;
            let mut rows = stmt.query_map(params![key], |row| {
                Ok(Preference {
                    id: row.get(0)?,
                    key: row.get(1)?,
                    value: row.get(2)?,
                    project: row.get(3)?,
                    confidence: row.get(4)?,
                    source: row.get(5)?,
                    created_at: row.get(6)?,
                    updated_at: row.get(7)?,
                })
            })?;
            Ok(rows.next().transpose()?)
        }
    }

    pub fn list_preferences(&self, project: Option<&str>) -> Result<Vec<Preference>, GremlinError> {
        let conn = self.conn.lock().unwrap();
        if let Some(p) = project {
            let mut stmt = conn.prepare(
                "SELECT id, key, value, project, confidence, source, created_at, updated_at FROM preferences WHERE project = ? ORDER BY confidence DESC"
            )?;
            let rows = stmt.query_map(params![project], |row| {
                Ok(Preference {
                    id: row.get(0)?,
                    key: row.get(1)?,
                    value: row.get(2)?,
                    project: row.get(3)?,
                    confidence: row.get(4)?,
                    source: row.get(5)?,
                    created_at: row.get(6)?,
                    updated_at: row.get(7)?,
                })
            })?;
            Ok(rows.filter_map(Result::ok).collect())
        } else {
            let mut stmt = conn.prepare(
                "SELECT id, key, value, project, confidence, source, created_at, updated_at FROM preferences ORDER BY confidence DESC"
            )?;
            let rows = stmt.query_map([], |row| {
                Ok(Preference {
                    id: row.get(0)?,
                    key: row.get(1)?,
                    value: row.get(2)?,
                    project: row.get(3)?,
                    confidence: row.get(4)?,
                    source: row.get(5)?,
                    created_at: row.get(6)?,
                    updated_at: row.get(7)?,
                })
            })?;
            Ok(rows.filter_map(Result::ok).collect())
        }
    }

    // ─── Recommendation operations ───

    pub fn add_recommendation(&self, rec: &Recommendation) -> Result<i64, GremlinError> {
        let conn = self.conn.lock().unwrap();
        conn.execute(
            "INSERT INTO recommendations (kind, title, description, confidence, context, action) VALUES (?, ?, ?, ?, ?, ?)",
            params![rec.kind, rec.title, rec.description, rec.confidence, rec.context, rec.action]
        )?;
        Ok(conn.last_insert_rowid())
    }

    pub fn get_recommendations(&self, include_dismissed: bool, limit: usize) -> Result<Vec<Recommendation>, GremlinError> {
        let conn = self.conn.lock().unwrap();
        let sql = if include_dismissed {
            "SELECT id, kind, title, description, confidence, context, action, created_at, dismissed FROM recommendations ORDER BY confidence DESC LIMIT ?"
        } else {
            "SELECT id, kind, title, description, confidence, context, action, created_at, dismissed FROM recommendations WHERE dismissed = 0 ORDER BY confidence DESC LIMIT ?"
        };
        let mut stmt = conn.prepare(sql)?;
        let rows = stmt.query_map(params![limit], |row| {
            Ok(Recommendation {
                id: row.get(0)?,
                kind: row.get(1)?,
                title: row.get(2)?,
                description: row.get(3)?,
                confidence: row.get(4)?,
                context: row.get(5)?,
                action: row.get(6)?,
                created_at: row.get(7)?,
                dismissed: row.get(8)?,
            })
        })?;
        Ok(rows.filter_map(Result::ok).collect())
    }

    pub fn dismiss_recommendation(&self, id: i64) -> Result<(), GremlinError> {
        let conn = self.conn.lock().unwrap();
        conn.execute("UPDATE recommendations SET dismissed = 1 WHERE id = ?", params![id])?;
        Ok(())
    }

    // ─── Self-modification operations ───

    pub fn propose_self_modification(&self, modif: &SelfModification) -> Result<i64, GremlinError> {
        let conn = self.conn.lock().unwrap();
        conn.execute(
            "INSERT INTO self_modifications (kind, title, description, diff, confidence) VALUES (?, ?, ?, ?, ?)",
            params![modif.kind, modif.title, modif.description, modif.diff, modif.confidence]
        )?;
        Ok(conn.last_insert_rowid())
    }

    pub fn get_self_modifications(&self, status: Option<&str>) -> Result<Vec<SelfModification>, GremlinError> {
        let conn = self.conn.lock().unwrap();
        if let Some(s) = status {
            let mut stmt = conn.prepare(
                "SELECT id, kind, title, description, diff, confidence, status, created_at, decided_at FROM self_modifications WHERE status = ? ORDER BY created_at DESC"
            )?;
            let rows = stmt.query_map(params![status], |row| {
                Ok(SelfModification {
                    id: row.get(0)?,
                    kind: row.get(1)?,
                    title: row.get(2)?,
                    description: row.get(3)?,
                    diff: row.get(4)?,
                    confidence: row.get(5)?,
                    status: row.get(6)?,
                    created_at: row.get(7)?,
                    decided_at: row.get(8)?,
                })
            })?;
            Ok(rows.filter_map(Result::ok).collect())
        } else {
            let mut stmt = conn.prepare(
                "SELECT id, kind, title, description, diff, confidence, status, created_at, decided_at FROM self_modifications ORDER BY created_at DESC"
            )?;
            let rows = stmt.query_map([], |row| {
                Ok(SelfModification {
                    id: row.get(0)?,
                    kind: row.get(1)?,
                    title: row.get(2)?,
                    description: row.get(3)?,
                    diff: row.get(4)?,
                    confidence: row.get(5)?,
                    status: row.get(6)?,
                    created_at: row.get(7)?,
                    decided_at: row.get(8)?,
                })
            })?;
            Ok(rows.filter_map(Result::ok).collect())
        }
    }

    pub fn decide_self_modification(&self, id: i64, approved: bool) -> Result<(), GremlinError> {
        let conn = self.conn.lock().unwrap();
        let status = if approved { "approved" } else { "rejected" };
        let now = chrono::Utc::now().to_rfc3339();
        conn.execute(
            "UPDATE self_modifications SET status = ?, decided_at = ? WHERE id = ?",
            params![status, now, id]
        )?;
        Ok(())
    }

    // ─── Vector search (requires sqlite-vec) ───

    pub fn store_embedding(&self, message_id: i64, vector: &[f32]) -> Result<(), GremlinError> {
        let conn = self.conn.lock().unwrap();
        let vec_bytes = vec_to_blob(vector);
        conn.execute(
            "INSERT INTO embeddings (message_id, vector) VALUES (?, ?)",
            params![message_id, vec_bytes]
        )?;
        Ok(())
    }

    pub fn vector_search(&self, query_vector: &[f32], limit: usize) -> Result<Vec<(i64, f32)>, GremlinError> {
        let conn = self.conn.lock().unwrap();
        let vec_bytes = vec_to_blob(query_vector);
        // Uses sqlite-vec's knn search
        let mut stmt = conn.prepare(
            "SELECT message_id, distance FROM vec_knn(embeddings, ?, ?) ORDER BY distance LIMIT ?"
        )?;
        let rows = stmt.query_map(params![&vec_bytes, limit], |row| {
            Ok((row.get(0)?, row.get(1)?))
        })?;
        Ok(rows.filter_map(Result::ok).collect())
    }

    // ─── Stats ───

    pub fn stats(&self) -> Result<MemoryStats, GremlinError> {
        let conn = self.conn.lock().unwrap();
        let conv_count: i64 = conn.query_row("SELECT COUNT(*) FROM conversations", [], |r| r.get(0))?;
        let fact_count: i64 = conn.query_row("SELECT COUNT(*) FROM facts", [], |r| r.get(0))?;
        let pref_count: i64 = conn.query_row("SELECT COUNT(*) FROM preferences", [], |r| r.get(0))?;
        let rec_count: i64 = conn.query_row("SELECT COUNT(*) FROM recommendations WHERE dismissed = 0", [], |r| r.get(0))?;
        let mod_count: i64 = conn.query_row("SELECT COUNT(*) FROM self_modifications WHERE status = 'proposed'", [], |r| r.get(0))?;
        let db_size: i64 = conn.query_row("SELECT page_count * page_size FROM pragma_page_count(), pragma_page_size()", [], |r| r.get(0))?;

        Ok(MemoryStats {
            conversations: conv_count,
            facts: fact_count,
            preferences: pref_count,
            recommendations: rec_count,
            proposed_modifications: mod_count,
            db_size_bytes: db_size,
        })
    }
}

/// Helper to convert f32 vec to sqlite-vec blob format
fn vec_to_blob(v: &[f32]) -> Vec<u8> {
    let mut buf = Vec::with_capacity(v.len() * 4 + 4);
    buf.extend_from_slice(&(v.len() as u32).to_le_bytes());
    for f in v {
        buf.extend_from_slice(&f.to_le_bytes());
    }
    buf
}

/// Statistics about the memory system
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MemoryStats {
    pub conversations: i64,
    pub facts: i64,
    pub preferences: i64,
    pub recommendations: i64,
    pub proposed_modifications: i64,
    pub db_size_bytes: i64,
}